version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: telegram_mini_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_TELEGRAM_IDS: ${ADMIN_TELEGRAM_IDS}
      ADMIN_PHONE_NUMBERS: ${ADMIN_PHONE_NUMBERS}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      API_PREFIX: ${API_PREFIX}
      ADDITIONAL_API_PREFIXES: ${ADDITIONAL_API_PREFIXES}
      PUBLIC_API_ROOTS: ${PUBLIC_API_ROOTS}
      MEDIA_ROOT: ${MEDIA_ROOT}
      MEDIA_URL: ${MEDIA_URL}
    volumes:
      - backend_uploads:/app/app/static/uploads
    depends_on:
      - db
    ports:
      - "8001:8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_BACKEND_API_PREFIX: ${VITE_BACKEND_API_PREFIX}
        VITE_ADMIN_TELEGRAM_IDS: ${VITE_ADMIN_TELEGRAM_IDS}
        VITE_ADMIN_PHONE_NUMBERS: ${VITE_ADMIN_PHONE_NUMBERS}
        VITE_FAKE_TELEGRAM_ID: ${VITE_FAKE_TELEGRAM_ID}
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "5173:80"

  bot:
    build:
      context: ./bot
    env_file:
      - .env
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      WEBAPP_URL: ${WEBAPP_URL}
      ADMIN_TELEGRAM_IDS: ${ADMIN_TELEGRAM_IDS}
    depends_on:
      - backend

volumes:
  db_data:
  backend_uploads:
