version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: telegram_mini_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_TELEGRAM_IDS: ${ADMIN_TELEGRAM_IDS}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      MEDIA_ROOT: ${MEDIA_ROOT}
      MEDIA_URL: ${MEDIA_URL}
    volumes:
      - backend_uploads:/app/app/static/uploads
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    environment:
      VITE_BACKEND_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "5173:80"

  bot:
    build:
      context: ./bot
    env_file:
      - .env
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      WEBAPP_URL: ${WEBAPP_URL}
      ADMIN_TELEGRAM_IDS: ${ADMIN_TELEGRAM_IDS}
    depends_on:
      - backend

volumes:
  db_data:
  backend_uploads:
